version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: pg-db

  web:
    image: python:3.9
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "pip install -r requirements.txt &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    container_name: web

volumes:
  db_data:
